apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
data:
  rclone.conf: |
    [minio]
    type = s3
    provider = Minio
    env_auth = false
    access_key_id = <your-access-key-id>
    secret_access_key = <your-secret-access-key>
    region = us-east-1
    endpoint = http://<your-minio-endpoint>
    location_constraint =
    server_side_encryption =
